-- Exploring countries in our customers_dataset
select distinct country 
from gold.dim_customers dc; 


--Exploring categories
select distinct category_id, product_category, subcategory, product_name 
from gold.dim_products dp 
order by category_id ;


SELECT *
FROM gold.fact_sales;

-- Exploring Dates in fact_sales
select 
 max(order_date) as latest_order
 , min(order_date) as earliest_order
 , extract(year from AGE(max(order_date), min(order_date))) as order_date_span_years
 , 12*(extract(year from AGE(max(order_date),min(order_date))))+ extract(month from age(max(order_date), min(order_date))) as order_date_span_months
from gold.fact_sales fs2 


-- Exploring Dates in customers dimension
select *
from gold.dim_customers dc ;

select
  min(birthdate) as earliest_birthdate
  , max(birthdate) as latest_birthdate
  , max(age(now(),birthdate)) as age_of_oldest_customer
  , min(age(now(),birthdate)) as age_of_youngest_customer
from gold.dim_customers dc;



-- Exploring measures
-- Fin the total sales
select sum(fs2.sales_amount) as total_sales from gold.fact_sales fs2 ;
-- Find how many items are sold
select sum(fs2.quantity) as total_items_sold from gold.fact_sales fs2;
-- Find the average selling price
select avg(price) as average_price from gold.fact_sales fs2;
-- Find the total number of orders
select count(distinct fs2.order_number) as total_humber_of_orders from gold.fact_sales fs2;
-- Find the total number of products
select count(distinct fs2.product_key) total_number_of_products from gold.dim_products fs2; 
-- Find the total number of customers
select count(customer_key) as total_num_customer from gold.dim_customers dc ;
-- Find the total number of customers that have placed an order
select count(distinct customer_key) customers_with_an_order from gold.fact_sales fs2 ;



-- Joining all queries

select 'Total Sales' as measure_name, sum(fs2.sales_amount) as measure_value from gold.fact_sales fs2
union
select 'Total Items Sold' as measure_name, sum(fs2.quantity) as measure_value from gold.fact_sales fs2
union
select 'Average Item Price' as measure_name, round(avg(price),2) as measure_value from gold.fact_sales fs2
union
select 'Total Number Of Orders' as measure_name, count(distinct fs2.order_number) as measure_value from gold.fact_sales fs2
union
select 'Total Number Of Products' as measure_name, count(distinct fs2.product_key) measure_value from gold.dim_products fs2
union
select 'Total Number Of Customers' as measure_name, count(customer_key) as measure_value from gold.dim_customers dc
union
select 'Customers That Have Placed An Order' as measure_name, count(distinct customer_key) measure_value from gold.fact_sales fs2;


-- Magnitude analysis

-- Find total customers by countries
select dc.country,
  count(dc.customer_key) as total_customers
from gold.dim_customers dc
group by 1
order by total_customers desc; 

-- Find total customers by gender
select 
  dc.gender,
  count(customer_key) as total_customers
from gold.dim_customers dc
group by 1
order by total_customers desc;

-- Find total products by category
SELECT
  dp.product_category as category_name
  , count(dp.product_key) AS total_products
FROM gold.dim_products dp
GROUP BY 1
order by total_products desc;

-- What is the average cost in each category?
select 
  dp.product_category as category_name
  , floor(avg(dp."cost"))::int as average_cost
from gold.dim_products dp
group by 1
order by average_cost desc;

-- What is the total revenue generated for each category?
select
  dp.product_category
  , sum(fs2.sales_amount) as total_revenue
from gold.dim_products dp
left join gold.fact_sales fs2 
  on dp.product_key = fs2.product_key 
group by 1
order by total_revenue desc 
;

-- Find total revenue generated by each customer
select
  dc.customer_key 
  , dc.first_name 
  , dc.last_name 
  , sum(fs2.sales_amount) as total_revenue
from gold.fact_sales fs2 
left join gold.dim_customers dc
  on fs2.customer_key = dc.customer_key 
group by 1,2,3
order by total_revenue desc

-- What is the distribution of sold items across countries?
select
  dc.country 
  , sum(fs2.quantity) as total_sold_items
from gold.fact_sales fs2 
left join gold.dim_customers dc 
  on fs2.customer_key = dc.customer_key 
group by 1
order by total_sold_items desc;



---- Ranking Analysis
-- Ranking measure values by a dimension
--- Which 5 products generate the highest revenue
with revenue_per_product as(
select
  dp.product_number
  , dp.product_name
  , sum(fs2.sales_amount) as product_revenue
  , row_number() over (order by sum(fs2.sales_amount) desc) as rn
from gold.fact_sales fs2 
left join gold.dim_products dp 
  on fs2.product_key = dp.product_key
group by 1,2)
select 
  rpp.product_number
  , rpp.product_name
  , rpp.product_revenue
from revenue_per_product rpp
where
  rpp.rn <=5
;

--- Worst performing 5 products
with revenue_per_product as(
select
  dp.product_number
  , dp.product_name
  , sum(fs2.sales_amount) as product_revenue
  , row_number() over (order by sum(fs2.sales_amount) asc) as rn
from gold.fact_sales fs2 
left join gold.dim_products dp 
  on fs2.product_key = dp.product_key
group by 1,2)
select 
  rpp.product_number
  , rpp.product_name
  , rpp.product_revenue
from revenue_per_product rpp
where
  rpp.rn <=5
;

-- Find the top 10 customers who have generated the highest revenue
select *
from(select 
  dc.customer_key 
  , dc.first_name 
  , dc.last_name 
  , sum(fs2.sales_amount) as customer_revenue
  , rank() over (order by sum(fs2.sales_amount) desc) as customer_rank
from gold.fact_sales fs2 
left join gold.dim_customers dc 
  on fs2.customer_key = dc.customer_key
group by 1,2,3) t
where t.customer_rank <=10;

-- Find the 3 customers with the fewest orders placed
select *
from (select
  dc.customer_key 
  , dc.first_name 
  , dc.last_name 
  , count(distinct fs2.order_number) as orders_placed
  , row_number() over (order by count(distinct fs2.order_number) asc) customer_rank
from gold.fact_sales fs2 
left join gold.dim_customers dc 
  on fs2.customer_key = dc.customer_key 
group by 1,2,3) t
where t.customer_rank <=3;
